main: cc.xacademy.xahousesystem.HousePlugin
name: XAHouseSystem
version: 0.1.1
api-version: 1.16
commands:
  givespecialitem:
    description: Gives you a special item from XA House System
    usage: /givespecialitem <item_name>
    permission: xahousesystem.staff
  o5vault:
    description: Opens a vault of goodies (O5 Council only)
    usage: /o5vault
    permission: xahousesystem.o5